artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://chicken-disease-dataset.s3.ap-south-1.amazonaws.com/chicken-disease-dataset.zip?response-content-disposition=attachment&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEBkaCmFwLXNvdXRoLTEiRzBFAiEA%2F5WYt0xCYsy9WAG9Xq20JpE41lmSykAp1aay21hVH%2FACIC683vKiJBXsJMhF7Cta9sPoknwlAMWGtOqK67CP%2BiDzKuQCCHIQAxoMMjc1MjIzNzg3OTYyIgx3CkdYeQvLeWnFdNkqwQKAP%2BpjAn1sCIRoIUqiQBiCUfRdaE62sKBoVgDYQ9iPP1HULx%2BgU1lDbRSmyIXw490kqAey1WyK2nrTmnjzbhS5W9vskmpS%2F3NvmTk8JMUpWkDENe4Q4tvmo50cdVD8ntZH4fUBlJV%2FdQbw3g%2FPoobLc8rxSR70RHOm1MvSJ45rXtnCU%2BghApf2HSRWD8q2vorr13v0qtapzQzOGJLHIyVtI6urNtgzJ3h1l0aYQOzqv9arZs2AO%2FlFFfZZpPgpfe5FBvIijnLEeExvS1uNkVTPNgTl%2FWUtHP6638A9IbD%2BNjCfitxuKjr5ESJZ%2Bhq9Vettu5h5pOuraHavw3MtckycXqL3Zgg1SusTmD0Za52Hh4jMOt9GDBmW9wdVvc96ge8rXhdD6ftHhL%2FDlQEsGPIaZIn1A6CH%2B6CibLr5qkNObf4w35C7pAY6swLcE1f9diSSDt4Nid4vd9Im%2BpH2Rn1YT0mAw4L9MbI8n0LrPG0vmFmN%2BwI152bZOUYW%2BVSna7Rx26D2DTKfnKcFXM2Jite9iAXU57wyi8YqU9wdRZXp6iWd38hpq%2BFRXbehRy92wHQLyxKBwDBUrsME8ptnJxZcwb%2FX1oMAFdWSco8gstTPk%2B7D%2BdIAcgK4T5%2FUAYiwLMDSXMuI0L7CxEPm3nb40pb850SYese9DRSct6IAWHU%2BlmcI1vj2U6jmolEF5H7zQfLbx2KjLua2oelWvvu5LTpFD7%2B0U21cDEBaU1igsD1AVIQJBTBmGqFPp8kfB%2FT1qP0ziAzMnvmIh6CXwdK7Un1pY8zDGZy7NmLfYExIxIKw0Df0zBJ7DZJidc4giTVf5%2BCZ77fww%2F92jZiDE7%2FB&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230618T174545Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAUAFE5XG5MS3T5T6Z%2F20230618%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Signature=34baf3ecfefe6bc67626deabc9a03a12d40568f7789da4ffa1f59d5d5a2b31be
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5